
import Head from 'next/head'

import HeaderItem from "./HeaderItem"
import { BsGithub, BsInstagram } from 'react-icons/bs'
import HeaderIcons from "./HeaderIcons"
import Link from 'next/link'

function Header() {
    return (
        <div>
            <Head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='' />
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet" />
                <title>Blog estudos</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        
            <div className="mt-3">
                <header className="flex p-5 justify-evenly items-center">

                    <div>
                        <h2 className="text-3xl	font-bold">BLOG</h2>
                    </div>

                    <div className="flex items-center">
                        <Link href='/'>
                            <a>
                                <HeaderItem item='Home'/>
                            </a>
                        </Link>
                        <HeaderItem item='Sobre'/>
                        <div className="flex border-l border-slate-200">
                            <HeaderIcons link={"https://github.com/fyoussef"}>
                                <BsGithub className="group-hover:animate-bounce text-2xl hover:text-gray-500 cursor-pointer" />
                            </HeaderIcons>
                            <HeaderIcons link={"https://www.instagram.com/yousseffilipi/"}>
                                <BsInstagram className="group-hover:animate-bounce text-2xl hover:text-gray-500 cursor-pointer" />
                            </HeaderIcons>
                        </div>
                    </div>

                    <div class="flex items-center justify-between">
                        <button className="bg-slate-900 hover:bg-slate-700 text-white font-bold py-2 w-32 rounded" type="button">
                            Login
                        </button>
                    </div>

                </header>
            </div>
            <div className="w-full h-px bg-gray-200" style={{opacity: '1', transformOrigin: '50% 50% 0px'}}></div>
        </div>

    )
}

export default Header