import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react';

export default function Home(props) {


  const { posts } = props;

  const [post, setPost] = useState(posts);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">
          {post.map((pst, key) => (
            pst.title
          ))}
      </h1>
    </div>
  )
}


export async function getStaticProps(context) {

  const post = await axios.get('http://localhost:3000/api/posts');
  const { data } = post;

  return {
    props: {
      posts: data
    },
  }
}