import Head from 'next/head'
import axios from 'axios'
import { useState } from 'react';

import Header from '../components/Header';
import HomeSection from '../components/HomeSection'
import PostsSection from '../components/PostsSection';

export default function Home(props) {


  const { posts } = props;

  const [post, setPost] = useState(posts);

  return (
    <div>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='' />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='mx-auto max-w-full'>

        <Header/>
          <div className="w-full h-px bg-gray-200" style={{opacity: '1', transformOrigin: '50% 50% 0px'}}></div>
        <HomeSection />

        <PostsSection />


      </div>
      
      
    </div>
  )
}


export async function getStaticProps(context) {

  const post = await axios.get('http://localhost:3000/api/posts');
  const { data } = post;

  return {
    props: {
      posts: data
    },
  }
}